import Provider from "./components/Provider"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body theme={"light"}>
        <Provider>
          <h1>testando</h1>
          {children}
        </Provider>
      </body>
    </html>
  )
}
